<!-- plugin dependencies -->
<script type="text/javascript" src="./vendors/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="./vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="./vendors/moment/moment.js"></script>
<script type="text/javascript" src="./vendors/metismenu/dist/metisMenu.js"></script>
<script type="text/javascript" src="./vendors/bootstrap4-toggle/js/bootstrap4-toggle.min.js"></script>
<script type="text/javascript" src="./vendors/jquery-circle-progress/dist/circle-progress.min.js"></script>
<script type="text/javascript" src="./vendors/perfect-scrollbar/dist/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="./vendors/toastr/build/toastr.min.js"></script>
<script type="text/javascript" src="./vendors/jquery.fancytree/dist/jquery.fancytree-all-deps.min.js"></script>
<script type="text/javascript" src="./vendors/apexcharts/dist/apexcharts.min.js"></script>
<!-- custome.js -->
<script type="text/javascript" src="./js/charts/apex-charts.js"></script>
<script type="text/javascript" src="./js/circle-progress.js"></script>
<script type="text/javascript" src="./js/demo.js"></script>
<script type="text/javascript" src="./js/scrollbar.js"></script>
<script type="text/javascript" src="./js/toastr.js"></script>
<script type="text/javascript" src="./js/treeview.js"></script>
<script type="text/javascript" src="./js/form-components/toggle-switch.js"></script>
<script type="text/javascript" src="./js/app.js"></script>